name: FaithDiff
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.12.14=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_1
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - pytorch=2.4.0=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.4.0=py310_cu124
  - torchtriton=3.0.0=py310
  - torchvision=0.19.0=py310_cu124
  - typing_extensions=4.12.2=py310h06a4308_0
  - urllib3=2.2.3=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==24.3.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.45.0
      - cfgv==3.4.0
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.2.0
      - decorator==5.1.1
      - deepspeed==0.15.1
      - dill==0.3.8
      - distlib==0.3.9
      - einops==0.7.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - facexlib==0.3.0
      - fastapi==0.115.6
      - ffmpy==0.5.0
      - filterpy==1.4.5
      - flatbuffers==24.12.23
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - ftfy==6.3.1
      - future==1.0.0
      - gast==0.6.0
      - gdown==5.2.0
      - google-pasta==0.2.0
      - gradio==5.0.0
      - gradio-client==1.4.0
      - grpcio==1.69.0
      - h11==0.14.0
      - h5py==3.12.1
      - hjson==3.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.25.2
      - icecream==2.1.3
      - identify==2.6.5
      - imageio==2.34.0
      - imageio-ffmpeg==0.5.1
      - iniconfig==2.0.0
      - ipdb==0.13.13
      - ipython==8.31.0
      - jedi==0.19.2
      - keras==3.8.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.43.0
      - lmdb==1.6.2
      - loguru==0.7.2
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - namex==0.0.8
      - ninja==1.11.1.3
      - nodeenv==1.9.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-ml-py==12.560.30
      - omegaconf==2.4.0.dev3
      - openai-clip==1.0.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.4.0
      - optree==0.13.1
      - orjson==3.10.13
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pre-commit==4.0.1
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - protobuf==5.29.2
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyiqa==0.1.13
      - pyparsing==3.2.1
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2024.2
      - regex==2024.11.6
      - rich==13.9.4
      - ruff==0.8.6
      - safetensors==0.4.3
      - scikit-image==0.25.0
      - scipy==1.15.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.41.3
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - tifffile==2024.12.12
      - timm==1.0.12
      - tokenizers==0.15.2
      - tomli==2.2.1
      - tomlkit==0.12.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.1
      - typer==0.15.1
      - tzdata==2024.2
      - uvicorn==0.34.0
      - virtualenv==20.28.1
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.18.3


